# Generated by Django 5.1.2 on 2024-10-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
                ('Date', models.DateField()),
                ('Batch_id', models.IntegerField()),
                ('Teacher_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=100)),
                ('Student_dept', models.CharField(max_length=20)),
                ('Student_email', models.CharField(max_length=100)),
                ('Student_batch_id', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_name', models.CharField(max_length=100)),
                ('Teacher_email', models.CharField(max_length=100)),
                ('Batch_assigned_id', models.IntegerField()),
            ],
        ),
    ]
