# Generated by Django 5.1.2 on 2024-10-26 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_classes_instructor_student_users_delete_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.users')),
            ],
        ),
        migrations.CreateModel(
            name='Studen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtu_roll_no', models.CharField(max_length=30)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='end_Time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='start_Time',
            new_name='start_time',
        ),
    ]
