# Generated by Django 5.1.2 on 2024-10-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_instructo_studen_delete_instructor_delete_student_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructo',
            new_name='Instructor',
        ),
        migrations.RenameModel(
            old_name='Studen',
            new_name='Student',
        ),
    ]
