# Generated by Django 5.1.2 on 2024-10-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_rename_instructo_instructor_rename_studen_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='teacher_id',
            new_name='instructor_id',
        ),
    ]
