services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn new_project.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "your-secret-key"
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: "localhost,127.0.0.1,example.com"
      - key: DATABASE_URL
        value: "postgres://username:password@host:port/database"
    plan: free
    regions:
      - oregon

databases:
  - name: default
    plan: free
    connectionString: "postgres://your-database-credentials"
