# Generated by Django 5.1.2 on 2024-11-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='instructor_id',
            new_name='instructor',
        ),
    ]
