# Generated by Django 5.1.2 on 2024-11-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_instructor_id_classes_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
