# Generated by Django 5.1.2 on 2024-11-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
