# Generated by Django 5.1.2 on 2024-11-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phase',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three')]),
        ),
    ]
