# Generated by Django 5.1.2 on 2024-11-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_student_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='id',
            new_name='class_id',
        ),
    ]
