# Generated by Django 5.1.3 on 2024-11-15 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_rename_id_classes_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GD_ExtemporePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer', models.CharField(max_length=225)),
                ('date', models.DateField()),
                ('round', models.CharField(choices=[('R1', 'round1'), ('R2', 'round2'), ('R3', 'round3'), ('R4', 'round4')], max_length=40)),
                ('remark', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.student')),
            ],
        ),
        migrations.CreateModel(
            name='HRPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer', models.CharField(max_length=225)),
                ('date', models.DateField()),
                ('round', models.CharField(choices=[('R1', 'round1'), ('R2', 'round2'), ('R3', 'round3'), ('R4', 'round4')], max_length=40)),
                ('remark', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.student')),
            ],
        ),
        migrations.CreateModel(
            name='TechPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer', models.CharField(max_length=225)),
                ('date', models.DateField()),
                ('round', models.CharField(choices=[('R1', 'round1'), ('R2', 'round2'), ('R3', 'round3'), ('R4', 'round4')], max_length=40)),
                ('remark', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.student')),
            ],
        ),
    ]
